"use client";
import { useEffect, useState } from "react";
import { io } from "socket.io-client";

const fleet = [
  ["MH 12 AB 4821", "Pune → Mumbai", "On route", "68", "4.21 km/L"], ["KA 01 MN 7712", "Bengaluru → Chennai", "On route", "91", "5.12 km/L"], ["RJ 14 GT 9067", "Jaipur → Delhi", "Idle", "72", "4.43 km/L"], ["DL 01 TR 2398", "Delhi → Lucknow", "On route", "88", "4.94 km/L"]
];
export default function Dashboard() {
  const [events, setEvents] = useState<string[]>(["Live connection ready — demo workspace"]);
  const [connected, setConnected] = useState(false);
  useEffect(() => { const socket = io({ path: "/socket.io", auth: { organizationId: "demo-org" } }); socket.on("connect", () => setConnected(true)); socket.on("disconnect", () => setConnected(false)); socket.on("alert:new", (a) => setEvents(x => [`${a.title}: ${a.detail}`, ...x].slice(0, 4))); return () => { socket.close(); }; }, []);
  return <main className="app"><aside><div className="brand"><span>◉</span> FleetPulse</div><small>WORKSPACE</small><nav><a className="active">▦ Overview</a><a>▣ Live Fleet</a><a>⌁ Routes</a><a>◉ Fuel Analytics</a><a>♙ Drivers</a><a>◎ Maintenance</a></nav><div className="whatsapp"><b>Connect WhatsApp</b><p>Send route and fuel alerts to drivers instantly.</p><button>Set up now</button></div></aside><section className="content"><header><div><h1>Good morning, Arjun</h1><p>Here’s how your fleet is performing today.</p></div><div className={connected ? "live" : "offline"}>● {connected ? "Live" : "Reconnecting"}</div></header><article className="hero"><div><small>FUEL EFFICIENCY OPPORTUNITY</small><h2>₹1,24,800 can be saved this month</h2><p>Based on idling, route deviations, and driver behaviour across your active fleet.</p></div><div><span>Potential diesel saved</span><strong>1,152 L</strong><span>Equivalent to 3.4% fleet improvement</span></div></article><div className="kpis">{[["Active vehicles","84 / 96","↑ 6% vs last week"],["Fuel efficiency","4.82 km/L","↑ 0.21 vs last week"],["Idle time","7.4 hrs","↑ 1.2 hrs needs attention"],["On-time delivery","93.6%","↑ 2.8% vs last week"]].map(([a,b,c]) => <article className="card" key={a}><small>{a}</small><strong>{b}</strong><em>{c}</em></article>)}</div><div className="grid"><article className="card chart"><h3>Fuel consumption</h3><div className="bars">▁▃▂▅▄▆▅█</div><p>Actual usage is 3.4% above expected this week.</p></article><article className="card alerts"><h3>Priority alerts</h3>{events.map((e, i) => <p key={i}><b>{i === 0 ? "● " : "○ "}</b>{e}</p>)}</article></div><div className="grid"><article className="card table"><h3>Fleet at a glance</h3><table><thead><tr><th>Vehicle</th><th>Current route</th><th>Status</th><th>Driver score</th><th>Efficiency</th></tr></thead><tbody>{fleet.map(r => <tr key={r[0]}>{r.map((c,i) => <td key={i}>{c}</td>)}</tr>)}</tbody></table></article><article className="card action"><h3>Today’s recommended action</h3><p>Reroute 3 vehicles around NH48 congestion and notify drivers before dispatch.</p><strong>₹8,460</strong><small>Estimated saving · 94 L diesel</small><button>Optimize 3 routes</button></article></div></section></main>;
}
